[dev]
  #command = "npm run start"  # Command to start your app server
  #targetPort = 3000           # Port on which your app server listens
  staticServerPort = 80   # Port on which the static server will listen